[hot-issue]
title = "YG LIFE ─ HOT ISSUE"
url = "https://yg-life.com/archives/category/hot-issue?lang=ko"
entrySelector = "ul.hot_issue_list li"
titleSelector = "h3.post-title"
linkSelector = "a"
contentSelector = "div.excerpt"
dateSelector = "span.magz-meta"
dateFormat = "yyyy.MM.dd hh:mm a"
imageSelector = "div.post-thumb img"
waitUntil = "networkidle"
onFail = "stale"

[musicvideo]
title = "YG LIFE ─ YG TV"
url = "https://yg-life.com/archives/category/musicvideo?lang=ko"
entrySelector = "div.post-archives.post-archives3 div[id^='post']"
titleSelector = "h3.post-title"
linkSelector = "h3.post-title a"
contentSelector = "span.magz-meta span"
dateSelector = "span.magz-meta span"
dateFormat = "yyyy.MM.dd hh:mm a"
imageSelector = "div.post-thumb img"
waitUntil = "networkidle"
onFail = "stale"
